version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
  - dependency-name: css-loader
    versions:
    - 5.0.2
